// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvewouwktdspqoazjdck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2ZXdvdXdrdGRzcHFvYXpqZGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjczNjQsImV4cCI6MjA1ODMwMzM2NH0.O8O5g_ijKOuZacW2wEaf-N_xtWH7Wfi6VAOXwFbO5c8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);